version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                VERSION: $VERSION
                COMMIT_HASH: $COMMIT_HASH
                BUILD_TIMESTAMP: $BUILD_TIMESTAMP
        image: "${IMG}:${TAG}"
        stop_signal: SIGINT
        stop_grace_period: 15s
        ports:
            - "8080:8080"